services:
  app:
    image: audiotranscription:0.0.1
    container_name: audiotranscription
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_audiotranscription=1
    ipc: host
    env_file:
      - ./.env
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ${DATA_DIR}:/app/data
volumes:
  app_data:
    external: false