services:
  app:
    image: audiotranscription:0.0.1
    container_name: audiotranscription
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_audiotranscription=1
    ipc: host
    environment:
        - DATA_INPUT_DIR=/app/data/input
        - DATA_OUTPUT_DIR=/app/data/output
        - HF_HOME=/app/data/.cache
        - TORCH_HOME=/app/data/.cache
    env_file:
      - ./.env
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ${INPUT_DIR}:/app/data/input
      - ${OUTPUT_DIR}:/app/data/output
      - ${MODEL_DIR}:/app/data/.cache
volumes:
  app_data:
    external: false